version: "3.2"
networks:
  cinetwork:
    driver: bridge

volumes:
  jenkins-data:

services:
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "18080:8080"
    networks:
      - cinetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
  postgres:
    networks: cinetwork
    restart:  always
    image:  postgres:10-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    tty:  true
